version: '3.8'

services:
  facilitaapp:
    build: ./
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $APP_LOCAL_PORT:$APP_DOCKER_PORT
    stdin_open: true
    tty: true

volumes: 
  db:
